name: "Podcast Generator"
author: "Rachit Singhal"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "DockerFile"
branding: 
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}